sudo: false
language: python
python: 2.7
env:
  - TOXENV=py27-django111-sqlite
  - TOXENV=py27-django111-mysql
  - TOXENV=py27-django111-postgres
  # Meta
  - TOXENV=project
cache:
  directories:
    - pootle/static/js/node_modules
    - pootle/assets
install: pip install tox===3.0.0
script:
  - tox -e $TOXENV
after_script:
  # logs might get truncated https://github.com/travis-ci/travis-ci/issues/6018
  - sleep 1
notifications:
  email:
    on_failure: always
    on_success: change
before_cache:
  # Force rebuilds by removing cache for 'master' builds
  - if [[ "$TRAVIS_BRANCH" == "master" && "$TRAVIS_PULL_REQUEST" == "false" ]]; then rm -rf pootle/static/js/node_modules/* pootle/assets/* pootle/assets/.webassets-cache;  fi
services:
  - redis-server
  - elasticsearch
  - mysql
